// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagerMVC_2212453.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250821070419_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Books", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Nguyễn Văn A",
                            CategoryID = 1,
                            ISBN = "aaa",
                            PublishedYear = 1900,
                            Title = "History"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Nguyễn Văn B",
                            CategoryID = 2,
                            ISBN = "bbb",
                            PublishedYear = 2000,
                            Title = "Agriculture"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Nguyễn Văn C",
                            CategoryID = 3,
                            ISBN = "ccc",
                            PublishedYear = 2009,
                            Title = "C# master"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Nguyễn Văn D",
                            CategoryID = 3,
                            ISBN = "ddd",
                            PublishedYear = 1950,
                            Title = "Cấu trúc dữ liệu và giải thuật"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Nguyễn Văn E",
                            CategoryID = 1,
                            ISBN = "eee",
                            PublishedYear = 1920,
                            Title = "EEEEE"
                        });
                });

            modelBuilder.Entity("Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Lịch sử",
                            Description = "aaaaa"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Xã hội",
                            Description = "bbbbbb"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Lập trình",
                            Description = "programming book"
                        });
                });

            modelBuilder.Entity("Models.Books", b =>
                {
                    b.HasOne("Models.Categories", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Categories", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
