//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPath
    {
        public int GroupPathID { get; set; }
        public int GroupID { get; set; }
        public int PathID { get; set; }
        public Nullable<int> AccessMaskID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Path Path { get; set; }
    }
}
