//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public string LogName { get; set; }
        public string LogDescription { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> LogCategoryID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Group Group { get; set; }
        public virtual LogCategory LogCategory { get; set; }
    }
}
