//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using MVCProject.Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Resources;

    public partial class Path
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Path()
        {
            this.GroupPaths = new HashSet<GroupPath>();
        }
    
        public int PathID { get; set; }
        [Display(Name = "PathName", ResourceType = typeof(DisplayName))]
        public string PathName { get; set; }
        [Display(Name = "PathDescription", ResourceType = typeof(DisplayName))]
        public string PathDescription { get; set; }
        [Display(Name = "PathURL", ResourceType = typeof(DisplayName))]
        public string PathURL { get; set; }
        [Display(Name = "ImageURL", ResourceType = typeof(DisplayName))]
        public string ImageURL { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> Display { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupPath> GroupPaths { get; set; }
    }
}
