//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace BlogMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        [Display(Name = "Tên tiếng Việt")]
        public string Title { get; set; }
        [Display(Name = "Tên tiếng Việt")]
        public string Content { get; set; }
   
        public int BlogId { get; set; }
  
        public virtual Blog Blog { get; set; }
    }
}
